"""Manifest and source constants for the bounded NASA ISS OEM validation fixture."""

from __future__ import annotations

from datetime import date, datetime, timezone
from typing import Final

from ..contracts import DatasetManifest, SourceAsset
from ..corpus_contracts import (
    CoordinateFrameKind,
    CoordinateFrameMetadata,
    CorpusDatasetMetadata,
    ObservationModality,
    PhysicalDomain,
    TimeBasis,
)


NASA_ISS_ADAPTER_ID: Final[str] = "space-orb-nasa-iss-oem"
NASA_ISS_ADAPTER_VERSION: Final[str] = "0.1.1"
NASA_ISS_DATASET_ID: Final[str] = "nasa-topo-iss-oem-2022-04-27-bounded-fixture"
NASA_ISS_SOURCE_ASSET_ID: Final[str] = "nasa-topo-iss-oem-20220427-bounded-extract"
NASA_ISS_ORIGINAL_SOURCE_ASSET_ID: Final[str] = "nasa-topo-iss-oem-20220427-full-source"
NASA_ISS_FIXTURE_URI: Final[str] = (
    "repository://tests/corpus/real_world/fixtures/nasa_iss_oem_20220427_excerpt.kvn"
)
NASA_ISS_SOURCE_SHA256: Final[str] = (
    "b74e25876f2c79a191e4cde111775bf4f4c6a8f00f6ea4656329f269b9841b28"
)
NASA_ISS_ORIGINAL_SOURCE_URL: Final[str] = (
    "https://gist.github.com/djflux/5061eae243d62c9fadefe610db729ad8/raw/"
    "02a720df6f2103a7a3af88b24f165c18634bca41/"
    "ISS.OEM_J2K_EPH-202204300946.txt"
)
NASA_ISS_CREATION_DATE: Final[datetime] = datetime(
    2022, 4, 27, 15, 5, 27, 413_000, tzinfo=timezone.utc
)
NASA_ISS_FIRST_STATE_EPOCH: Final[datetime] = datetime(
    2022, 4, 27, 12, 0, tzinfo=timezone.utc
)
NASA_ISS_LAST_STATE_EPOCH: Final[datetime] = datetime(
    2022, 4, 27, 12, 48, tzinfo=timezone.utc
)


def _nasa_iss_frame() -> CoordinateFrameMetadata:
    return CoordinateFrameMetadata(
        frame_id="EME2000",
        kind=CoordinateFrameKind.ECI,
        axes_description=(
            "Earth-centered inertial Cartesian X/Y/Z axes in the OEM-declared "
            "Earth Mean Equator and Equinox of J2000 frame."
        ),
        origin_description="Earth geocenter",
        authority="CCSDS OEM metadata supplied by NASA/JSC/FOD/TOPO",
        epoch="J2000 frame definition",
        notes=(
            "The source metadata declares EME2000 and UTC.",
            "Only km-to-m and km/s-to-m/s conversions are applied.",
            "No propagation or Earth-fixed transformation is introduced.",
        ),
    )
####


def build_nasa_iss_corpus_metadata() -> CorpusDatasetMetadata:
    """Build the immutable Product 4 dataset envelope for the admitted fixture."""

    frame = _nasa_iss_frame()
    manifest = DatasetManifest(
        dataset_id=NASA_ISS_DATASET_ID,
        title="NASA TOPO ISS CCSDS OEM bounded inertial fixture",
        version="creation-20220427T150527.413Z@gist-02a720df6f21",
        publisher="NASA/JSC/FOD/TOPO",
        citation=(
            "NASA ISS Trajectory Data, CCSDS OEM generated by the ISS "
            "Trajectory Operations and Planning Officer; bounded immutable extract."
        ),
        doi=None,
        license_id="US-PD",
        license_url="http://www.usa.gov/publicdomain/label/1.0/",
        landing_page_url="https://spotthestation.nasa.gov/trajectory_data.cfm",
        accessed_on=date(2026, 8, 23),
        adapter_id=NASA_ISS_ADAPTER_ID,
        adapter_version=NASA_ISS_ADAPTER_VERSION,
        coordinate_frame="EME2000",
        nominal_sample_interval_s=240.0,
        source_assets=(
            SourceAsset(
                asset_id=NASA_ISS_SOURCE_ASSET_ID,
                title=(
                    "Exact committed 13-state extract from the NASA TOPO ISS OEM "
                    "created 2022-04-27"
                ),
                download_url=NASA_ISS_FIXTURE_URI,
                media_type="text/plain; profile=CCSDS-OEM-2.0-KVN-extract",
                sha256=NASA_ISS_SOURCE_SHA256,
                required=True,
            ),
            SourceAsset(
                asset_id=NASA_ISS_ORIGINAL_SOURCE_ASSET_ID,
                title="Immutable full NASA TOPO ISS OEM source product",
                download_url=NASA_ISS_ORIGINAL_SOURCE_URL,
                media_type="text/plain; profile=CCSDS-OEM-2.0-KVN",
                sha256=None,
                required=False,
            ),
        ),
        notes=(
            "The required asset URI resolves to the exact committed bounded fixture.",
            "The optional source asset records the immutable full-product provenance.",
            "The product is an operational predicted trajectory, not measurement truth.",
            "Object identity is retained for grouping and audit, not classifier features.",
        ),
    )
    return CorpusDatasetMetadata(
        dataset_manifest=manifest,
        domains=(PhysicalDomain.SPACE,),
        observation_modalities=(ObservationModality.OTHER,),
        native_coordinate_frame="EME2000 Earth-centered inertial Cartesian states",
        canonical_frame=frame,
        time_basis=TimeBasis.UNIX_UTC_SECONDS,
        source_type="operational_predicted_orbit_ephemeris",
        extensions={
            "source_message_type": "CCSDS_OEM_2.0",
            "source_state_role": "estimate",
            "value_basis": "operational_prediction",
            "source_time_system": "UTC",
            "source_frame": "EME2000",
            "source_velocity_available": True,
            "propagation_required": False,
            "rights_status": "US-PD",
            "validation_fixture_only": True,
        },
    )
####


__all__ = [
    "NASA_ISS_ADAPTER_ID",
    "NASA_ISS_ADAPTER_VERSION",
    "NASA_ISS_CREATION_DATE",
    "NASA_ISS_DATASET_ID",
    "NASA_ISS_FIRST_STATE_EPOCH",
    "NASA_ISS_FIXTURE_URI",
    "NASA_ISS_LAST_STATE_EPOCH",
    "NASA_ISS_ORIGINAL_SOURCE_ASSET_ID",
    "NASA_ISS_ORIGINAL_SOURCE_URL",
    "NASA_ISS_SOURCE_ASSET_ID",
    "NASA_ISS_SOURCE_SHA256",
    "build_nasa_iss_corpus_metadata",
]
