from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path

from ..markdown_builder import MarkdownDocument
from ..utils.io import _write_json, _write_text, write_csv
from ..utils.plotting import _figure_to_png, plt


@dataclass(frozen=True, slots=True)
class AlgorithmCoverageEntry:
    method_id: str
    method_name: str
    lane: str
    status: str
    online: bool
    offline: bool
    interpretable: bool
    posterior_native: bool
    calibratable: bool
    works_with_small_data: bool
    uses_dynamics: bool
    handles_switching: bool
    handles_nonlinearity: bool
    handles_nongaussianity: bool
    needs_training_data: bool
    ready_1d: bool
    lift_ready_3d: bool
    notes: str


@dataclass(frozen=True, slots=True)
class AlgorithmCoverageMatrixResult:
    entries: tuple[AlgorithmCoverageEntry, ...]
    summary: dict[str, object]
    report_markdown: str


@dataclass(frozen=True, slots=True)
class AlgorithmCoverageMatrixArtifacts:
    run_dir: Path
    report_path: Path
    summary_path: Path
    matrix_path: Path
    inventory_path: Path
    plot_path: Path


ALGORITHM_COVERAGE_MATRIX: tuple[AlgorithmCoverageEntry, ...] = (
    AlgorithmCoverageEntry(
        method_id="pointwise_likelihood",
        method_name="Pointwise likelihood",
        lane="core_physics_probabilistic",
        status="implemented",
        online=True,
        offline=False,
        interpretable=True,
        posterior_native=True,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=False,
        handles_nongaussianity=False,
        needs_training_data=False,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Lower-bound rung for instantaneous evidence only.",
    ),
    AlgorithmCoverageEntry(
        method_id="windowed_feature_likelihood",
        method_name="Windowed feature likelihood",
        lane="core_physics_probabilistic",
        status="implemented",
        online=True,
        offline=True,
        interpretable=True,
        posterior_native=True,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=False,
        handles_nongaussianity=False,
        needs_training_data=False,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Adds local history without a state-space model.",
    ),
    AlgorithmCoverageEntry(
        method_id="sequential_bayes",
        method_name="Sequential Bayesian accumulator",
        lane="core_physics_probabilistic",
        status="implemented",
        online=True,
        offline=True,
        interpretable=True,
        posterior_native=True,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=False,
        handles_nongaussianity=False,
        needs_training_data=False,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Shared posterior contract for accumulating evidence over time.",
    ),
    AlgorithmCoverageEntry(
        method_id="model_residual_bayes",
        method_name="Model residual Bayes",
        lane="core_physics_probabilistic",
        status="planned_near_term",
        online=True,
        offline=True,
        interpretable=True,
        posterior_native=True,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=True,
        handles_switching=False,
        handles_nonlinearity=False,
        handles_nongaussianity=False,
        needs_training_data=False,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Natural bridge from engineered features to residual-based evidence.",
    ),
    AlgorithmCoverageEntry(
        method_id="changepoint_detection",
        method_name="BOCPD / PELT changepoint detector",
        lane="core_physics_probabilistic",
        status="planned_near_term",
        online=True,
        offline=True,
        interpretable=True,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=False,
        handles_switching=True,
        handles_nonlinearity=False,
        handles_nongaussianity=False,
        needs_training_data=False,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Useful before IMM when the question is switch timing rather than full multi-model filtering.",
    ),
    AlgorithmCoverageEntry(
        method_id="transition_hmm",
        method_name="Transition HMM / class transition matrix",
        lane="core_physics_probabilistic",
        status="implemented",
        online=True,
        offline=True,
        interpretable=True,
        posterior_native=True,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=False,
        handles_switching=True,
        handles_nonlinearity=False,
        handles_nongaussianity=False,
        needs_training_data=False,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Explicit label-transition logic without continuous-state mixing.",
    ),
    AlgorithmCoverageEntry(
        method_id="kalman_bank",
        method_name="Kalman bank",
        lane="core_physics_probabilistic",
        status="implemented",
        online=True,
        offline=True,
        interpretable=True,
        posterior_native=True,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=True,
        handles_switching=False,
        handles_nonlinearity=False,
        handles_nongaussianity=False,
        needs_training_data=False,
        ready_1d=True,
        lift_ready_3d=True,
        notes="First model-based evidence provider in the ladder.",
    ),
    AlgorithmCoverageEntry(
        method_id="ukf_ekf_ckf",
        method_name="EKF / UKF / CKF family",
        lane="core_physics_probabilistic",
        status="planned_near_term",
        online=True,
        offline=True,
        interpretable=True,
        posterior_native=True,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=True,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=False,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Intermediate nonlinear filter rung before particle methods.",
    ),
    AlgorithmCoverageEntry(
        method_id="gaussian_sum_filter",
        method_name="Gaussian-sum filter",
        lane="core_physics_probabilistic",
        status="planned_near_term",
        online=True,
        offline=True,
        interpretable=True,
        posterior_native=True,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=True,
        handles_switching=True,
        handles_nonlinearity=True,
        handles_nongaussianity=True,
        needs_training_data=False,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Useful when one Gaussian is too restrictive but full PF is premature.",
    ),
    AlgorithmCoverageEntry(
        method_id="imm",
        method_name="IMM / switching Kalman family",
        lane="core_physics_probabilistic",
        status="implemented",
        online=True,
        offline=True,
        interpretable=True,
        posterior_native=True,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=True,
        handles_switching=True,
        handles_nonlinearity=False,
        handles_nongaussianity=False,
        needs_training_data=False,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Promoted on switching witnesses, but still witness-scoped rather than universal.",
    ),
    AlgorithmCoverageEntry(
        method_id="particle_filter",
        method_name="Particle filter",
        lane="core_physics_probabilistic",
        status="implemented",
        online=True,
        offline=True,
        interpretable=True,
        posterior_native=True,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=True,
        handles_switching=True,
        handles_nonlinearity=True,
        handles_nongaussianity=True,
        needs_training_data=False,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Promoted only on demonstrated nonlinear or non-Gaussian witnesses.",
    ),
    AlgorithmCoverageEntry(
        method_id="rbpf",
        method_name="Rao-Blackwellized particle filter",
        lane="core_physics_probabilistic",
        status="implemented",
        online=True,
        offline=True,
        interpretable=True,
        posterior_native=True,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=True,
        handles_switching=True,
        handles_nonlinearity=True,
        handles_nongaussianity=True,
        needs_training_data=False,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Used when sampled latent structure and analytic conditional state are both present.",
    ),
    AlgorithmCoverageEntry(
        method_id="rocket_family",
        method_name="ROCKET / MiniRocket / MultiRocket",
        lane="time_series_baselines",
        status="benchmark_candidate",
        online=False,
        offline=True,
        interpretable=False,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=True,
        notes="High-value fast TSC baseline before heavy neural sequence models.",
    ),
    AlgorithmCoverageEntry(
        method_id="dtw_knn",
        method_name="DTW / kNN",
        lane="time_series_baselines",
        status="benchmark_candidate",
        online=False,
        offline=True,
        interpretable=True,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=False,
        notes="Classic distance-based baseline so the repo does not skip the canonical TSC reference family.",
    ),
    AlgorithmCoverageEntry(
        method_id="shapelet_family",
        method_name="Shapelets / motif transforms",
        lane="time_series_baselines",
        status="benchmark_candidate",
        online=False,
        offline=True,
        interpretable=True,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=False,
        notes="Localized discriminative pattern lane for maneuver motifs and short witness signatures.",
    ),
    AlgorithmCoverageEntry(
        method_id="drcif_interval_forests",
        method_name="DrCIF / interval forests",
        lane="time_series_baselines",
        status="benchmark_candidate",
        online=False,
        offline=True,
        interpretable=False,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Strong interval-feature ensemble family for modern benchmark coverage.",
    ),
    AlgorithmCoverageEntry(
        method_id="dictionary_tde_family",
        method_name="BOSS / WEASEL / TDE dictionary methods",
        lane="time_series_baselines",
        status="benchmark_candidate",
        online=False,
        offline=True,
        interpretable=False,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=False,
        notes="Bag-of-patterns lane for symbolic and dictionary-style TSC baselines.",
    ),
    AlgorithmCoverageEntry(
        method_id="hive_cote",
        method_name="HIVE-COTE 2.0",
        lane="time_series_baselines",
        status="benchmark_candidate",
        online=False,
        offline=True,
        interpretable=False,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=False,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Strong benchmark lane representative, but heavier than the initial proof ladder.",
    ),
    AlgorithmCoverageEntry(
        method_id="gradient_boosted_features",
        method_name="Gradient boosting on engineered features",
        lane="time_series_baselines",
        status="benchmark_candidate",
        online=False,
        offline=True,
        interpretable=True,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Good bridge baseline for comparing feature engineering against non-neural learners.",
    ),
    AlgorithmCoverageEntry(
        method_id="tcn_inceptiontime",
        method_name="TCN / InceptionTime",
        lane="neural_sequence",
        status="research_candidate",
        online=True,
        offline=True,
        interpretable=False,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=False,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Reasonable first neural sequence baseline lane for the repo.",
    ),
    AlgorithmCoverageEntry(
        method_id="lstm_gru",
        method_name="LSTM / GRU",
        lane="neural_sequence",
        status="research_candidate",
        online=True,
        offline=True,
        interpretable=False,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=False,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Canonical recurrent baseline lane kept for comparison rather than as the target architecture.",
    ),
    AlgorithmCoverageEntry(
        method_id="patchtst_style_encoder",
        method_name="PatchTST-style encoder",
        lane="neural_sequence",
        status="watchlist",
        online=False,
        offline=True,
        interpretable=False,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=False,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Forecasting-inspired patched encoder idea tracked as a classifier-backbone candidate.",
    ),
    AlgorithmCoverageEntry(
        method_id="transformer_timesnet_s4",
        method_name="Transformer / TimesNet / S4 / Mamba",
        lane="neural_sequence",
        status="watchlist",
        online=True,
        offline=True,
        interpretable=False,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=False,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Tracked as stronger research backbones, not first-pass methodology proof targets.",
    ),
    AlgorithmCoverageEntry(
        method_id="ts2vec_family",
        method_name="TS2Vec / contrastive trajectory encoder",
        lane="representation_learning",
        status="research_candidate",
        online=False,
        offline=True,
        interpretable=False,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=False,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Representation-learning lane for future unlabeled or weak-label corpora.",
    ),
    AlgorithmCoverageEntry(
        method_id="ts_tcc_softclt",
        method_name="TS-TCC / SoftCLT",
        lane="representation_learning",
        status="watchlist",
        online=False,
        offline=True,
        interpretable=False,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=False,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Follow-on contrastive representation lane once a first embedding benchmark exists.",
    ),
    AlgorithmCoverageEntry(
        method_id="masked_timeseries_autoencoder",
        method_name="Masked time-series autoencoder",
        lane="representation_learning",
        status="watchlist",
        online=False,
        offline=True,
        interpretable=False,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=False,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Self-supervised reconstruction lane for large unlabeled trajectory corpora.",
    ),
    AlgorithmCoverageEntry(
        method_id="kalmannet_family",
        method_name="KalmanNet / learned-gain filters",
        lane="learned_filters",
        status="research_candidate",
        online=True,
        offline=True,
        interpretable=False,
        posterior_native=True,
        calibratable=True,
        works_with_small_data=False,
        uses_dynamics=True,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Neural bridge between classical filtering and deep sequence models.",
    ),
    AlgorithmCoverageEntry(
        method_id="deep_state_space_models",
        method_name="Differentiable Kalman / deep state-space models",
        lane="learned_filters",
        status="research_candidate",
        online=True,
        offline=True,
        interpretable=False,
        posterior_native=True,
        calibratable=True,
        works_with_small_data=False,
        uses_dynamics=True,
        handles_switching=True,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Structured learned-filter lane for partially known dynamics and learned gains or emissions.",
    ),
    AlgorithmCoverageEntry(
        method_id="koopman_classifier",
        method_name="Koopman / DMD residual classifier",
        lane="learned_filters",
        status="research_candidate",
        online=True,
        offline=True,
        interpretable=True,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=False,
        uses_dynamics=True,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Candidate middle ground between linear dynamics and black-box neural models.",
    ),
    AlgorithmCoverageEntry(
        method_id="calibration_wrappers",
        method_name="Temperature / isotonic / conformal wrappers",
        lane="calibration_uncertainty",
        status="planned_near_term",
        online=True,
        offline=True,
        interpretable=True,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=False,
        handles_nongaussianity=True,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Uncertainty lane should wrap existing evidence providers rather than replace them.",
    ),
    AlgorithmCoverageEntry(
        method_id="deep_uncertainty_wrappers",
        method_name="Deep ensembles / MC dropout / evidential wrappers",
        lane="calibration_uncertainty",
        status="research_candidate",
        online=True,
        offline=True,
        interpretable=False,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=False,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=True,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Experimental uncertainty lane for learned models; should be audited rather than trusted by default.",
    ),
    AlgorithmCoverageEntry(
        method_id="ood_detection",
        method_name="OOD detection / abstention",
        lane="calibration_uncertainty",
        status="planned_near_term",
        online=True,
        offline=True,
        interpretable=True,
        posterior_native=False,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=False,
        handles_nongaussianity=True,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Decision-card lane for classify, defer, abstain, or request more evidence.",
    ),
    AlgorithmCoverageEntry(
        method_id="cem_cmaes",
        method_name="CEM / CMA-ES",
        lane="optimizer_generator",
        status="implemented_or_planned",
        online=False,
        offline=True,
        interpretable=True,
        posterior_native=False,
        calibratable=False,
        works_with_small_data=True,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=False,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Primary non-RL search lane for trajectory proposal and witness generation.",
    ),
    AlgorithmCoverageEntry(
        method_id="random_doe_search",
        method_name="Random search / grid / Latin hypercube",
        lane="optimizer_generator",
        status="implemented",
        online=False,
        offline=True,
        interpretable=True,
        posterior_native=False,
        calibratable=False,
        works_with_small_data=True,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=False,
        handles_nongaussianity=False,
        needs_training_data=False,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Default cheap search lane and control baseline for more advanced generator backends.",
    ),
    AlgorithmCoverageEntry(
        method_id="map_elites",
        method_name="MAP-Elites / quality-diversity archive",
        lane="optimizer_generator",
        status="implemented",
        online=False,
        offline=True,
        interpretable=True,
        posterior_native=False,
        calibratable=False,
        works_with_small_data=True,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=False,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Best current diverse corpus-space exploration lane.",
    ),
    AlgorithmCoverageEntry(
        method_id="ppo_sac_td3",
        method_name="PPO / SAC / TD3 sequential control",
        lane="optimizer_generator",
        status="experimental",
        online=True,
        offline=True,
        interpretable=False,
        posterior_native=False,
        calibratable=False,
        works_with_small_data=False,
        uses_dynamics=False,
        handles_switching=True,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=True,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Sequential-control generator lane for witnesses where timing and control history matter.",
    ),
    AlgorithmCoverageEntry(
        method_id="bayesian_optimization",
        method_name="Bayesian optimization",
        lane="optimizer_generator",
        status="planned_near_term",
        online=False,
        offline=True,
        interpretable=True,
        posterior_native=False,
        calibratable=False,
        works_with_small_data=True,
        uses_dynamics=False,
        handles_switching=False,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=False,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Sample-efficient black-box optimizer candidate for expensive trajectory objectives.",
    ),
    AlgorithmCoverageEntry(
        method_id="mpc_adversarial_generator",
        method_name="MPC-style adversarial generator",
        lane="optimizer_generator",
        status="research_candidate",
        online=True,
        offline=True,
        interpretable=True,
        posterior_native=False,
        calibratable=False,
        works_with_small_data=False,
        uses_dynamics=True,
        handles_switching=True,
        handles_nonlinearity=True,
        handles_nongaussianity=False,
        needs_training_data=False,
        ready_1d=True,
        lift_ready_3d=True,
        notes="Trajectory-optimization lane for sequential adversarial witness generation.",
    ),
    AlgorithmCoverageEntry(
        method_id="jpda_mht",
        method_name="JPDA / MHT family",
        lane="tracking_fusion_extension",
        status="future_extension",
        online=True,
        offline=True,
        interpretable=True,
        posterior_native=True,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=True,
        handles_switching=True,
        handles_nonlinearity=False,
        handles_nongaussianity=False,
        needs_training_data=False,
        ready_1d=False,
        lift_ready_3d=True,
        notes="Future multi-track data-association lane, intentionally outside the current single-track sandbox.",
    ),
    AlgorithmCoverageEntry(
        method_id="glmb_pmbm",
        method_name="GLMB / PMBM random-finite-set trackers",
        lane="tracking_fusion_extension",
        status="future_extension",
        online=True,
        offline=True,
        interpretable=True,
        posterior_native=True,
        calibratable=True,
        works_with_small_data=True,
        uses_dynamics=True,
        handles_switching=True,
        handles_nonlinearity=True,
        handles_nongaussianity=True,
        needs_training_data=False,
        ready_1d=False,
        lift_ready_3d=True,
        notes="Roadmap lane for clutter, births/deaths, and multi-target 3D fusion.",
    ),
)

_BOOLEAN_COLUMNS: tuple[str, ...] = (
    "online",
    "offline",
    "interpretable",
    "posterior_native",
    "calibratable",
    "works_with_small_data",
    "uses_dynamics",
    "handles_switching",
    "handles_nonlinearity",
    "handles_nongaussianity",
    "needs_training_data",
    "ready_1d",
    "lift_ready_3d",
)


def analyze_algorithm_coverage_matrix() -> AlgorithmCoverageMatrixResult:
    lane_counts: dict[str, int] = {}
    status_counts: dict[str, int] = {}
    for entry in ALGORITHM_COVERAGE_MATRIX:
        lane_counts[entry.lane] = lane_counts.get(entry.lane, 0) + 1
        status_counts[entry.status] = status_counts.get(entry.status, 0) + 1

    summary = {
        "entry_count": len(ALGORITHM_COVERAGE_MATRIX),
        "lane_count": len(lane_counts),
        "lanes": dict(sorted(lane_counts.items())),
        "statuses": dict(sorted(status_counts.items())),
        "implemented_count": sum(1 for entry in ALGORITHM_COVERAGE_MATRIX if entry.status == "implemented"),
        "ready_1d_count": sum(1 for entry in ALGORITHM_COVERAGE_MATRIX if entry.ready_1d),
        "lift_ready_3d_count": sum(1 for entry in ALGORITHM_COVERAGE_MATRIX if entry.lift_ready_3d),
    }
    return AlgorithmCoverageMatrixResult(
        entries=ALGORITHM_COVERAGE_MATRIX,
        summary=summary,
        report_markdown=render_algorithm_coverage_matrix_report(ALGORITHM_COVERAGE_MATRIX, summary),
    )


def render_algorithm_coverage_matrix_report(
    entries: tuple[AlgorithmCoverageEntry, ...],
    summary: dict[str, object],
) -> str:
    report = MarkdownDocument("Algorithm Coverage Matrix")
    report.paragraph(
        "This surface complements the proof ladder. The ladder remains the disciplined promotion path for methods we actively justify with witnesses, while this matrix shows the broader algorithm landscape the repo explicitly tracks."
    )
    report.heading("Coverage Summary", level=2)
    report.bullet_list(
        [
            f"Tracked entries: `{summary['entry_count']}`",
            f"Tracked lanes: `{summary['lane_count']}`",
            f"Implemented rows: `{summary['implemented_count']}`",
            f"1D-ready rows: `{summary['ready_1d_count']}`",
            f"3D-lift-ready rows: `{summary['lift_ready_3d_count']}`",
        ]
    )
    report.heading("Lane Intent", level=2)
    report.bullet_list(
        [
            "`core_physics_probabilistic`: the promotion ladder that produces comparable posterior histories and filter diagnostics.",
            "`time_series_baselines`: modern TSC baselines so the repo does not ignore non-physics classifiers.",
            "`neural_sequence` and `representation_learning`: research lanes for sequence learners and reusable embeddings.",
            "`learned_filters`: hybrid physics-plus-learning candidates such as KalmanNet and Koopman residual models.",
            "`calibration_uncertainty`: wrappers that govern abstention, coverage, and confidence rather than replacing evidence providers.",
            "`optimizer_generator`: corpus and witness generation methods, including black-box search and RL.",
            "`tracking_fusion_extension`: future multi-target and 3D data-association roadmaps, intentionally outside the current single-track ladder.",
        ]
    )
    report.heading("Representative Rows", level=2)
    preview_rows = [
        (entry.method_name, entry.lane, entry.status, "yes" if entry.online else "no", "yes" if entry.lift_ready_3d else "no")
        for entry in entries
    ]
    report.table(
        ["Method", "Lane", "Status", "Online", "3D-lift-ready"],
        preview_rows,
    )
    report.heading("Reading Rule", level=2)
    report.bullet_list(
        [
            "A row appearing here does not imply implementation or promotion.",
            "Rows marked `implemented`, `implemented_or_planned`, or `experimental` should have concrete repo artifacts, code scaffolding, or tests.",
            "Rows marked `benchmark_candidate`, `planned_near_term`, `research_candidate`, or `watchlist` are tracked so the roadmap stays explicit and disciplined.",
            "Future 3D and multi-target methods stay visible here without polluting the 1D proof ladder.",
        ]
    )
    return report.text()


def _render_algorithm_coverage_plot(entries: tuple[AlgorithmCoverageEntry, ...]):
    matrix = [
        [1 if getattr(entry, column) else 0 for column in _BOOLEAN_COLUMNS]
        for entry in entries
    ]
    fig_height = max(7.0, 0.38 * len(entries))
    fig, ax = plt.subplots(figsize=(14, fig_height))
    image = ax.imshow(matrix, aspect="auto", cmap="Blues", vmin=0, vmax=1)
    ax.set_xticks(range(len(_BOOLEAN_COLUMNS)))
    ax.set_xticklabels([column.replace("_", "\n") for column in _BOOLEAN_COLUMNS], rotation=0, fontsize=8)
    ax.set_yticks(range(len(entries)))
    ax.set_yticklabels([entry.method_id for entry in entries], fontsize=8)
    ax.set_title("Algorithm Coverage Matrix", fontsize=13, fontweight="bold", loc="left")
    ax.set_xlabel("Capability")
    ax.set_ylabel("Tracked method")
    ax.set_xticks([index - 0.5 for index in range(1, len(_BOOLEAN_COLUMNS))], minor=True)
    ax.set_yticks([index - 0.5 for index in range(1, len(entries))], minor=True)
    ax.grid(which="minor", color="#d1d5db", linestyle="-", linewidth=0.5)
    ax.tick_params(which="minor", bottom=False, left=False)
    colorbar = fig.colorbar(image, ax=ax, fraction=0.024, pad=0.02)
    colorbar.set_ticks([0, 1])
    colorbar.set_ticklabels(["no", "yes"])
    fig.tight_layout()
    return fig


def write_algorithm_coverage_matrix_artifacts(
    output_dir: str | Path,
    *,
    result: AlgorithmCoverageMatrixResult | None = None,
) -> AlgorithmCoverageMatrixArtifacts:
    payload = result or analyze_algorithm_coverage_matrix()
    output_root = Path(output_dir)
    run_dir = output_root / "algorithm_coverage_matrix_v1"
    run_dir.mkdir(parents=True, exist_ok=True)

    report_path = run_dir / "algorithm_coverage_matrix_report.md"
    summary_path = run_dir / "algorithm_coverage_matrix_summary.json"
    matrix_path = run_dir / "algorithm_coverage_matrix.csv"
    inventory_path = run_dir / "algorithm_coverage_matrix_inventory.json"
    plot_path = run_dir / "algorithm_coverage_matrix.png"

    _write_text(report_path, payload.report_markdown)
    _write_json(summary_path, payload.summary)
    write_csv(
        matrix_path,
        [asdict(entry) for entry in payload.entries],
        [
            "method_id",
            "method_name",
            "lane",
            "status",
            *_BOOLEAN_COLUMNS,
            "notes",
        ],
    )
    _write_json(inventory_path, [asdict(entry) for entry in payload.entries])
    plot_path.write_bytes(_figure_to_png(_render_algorithm_coverage_plot(payload.entries)))
    return AlgorithmCoverageMatrixArtifacts(
        run_dir=run_dir,
        report_path=report_path,
        summary_path=summary_path,
        matrix_path=matrix_path,
        inventory_path=inventory_path,
        plot_path=plot_path,
    )
