from __future__ import annotations

from io import BytesIO
from pathlib import Path
from typing import Any, Iterator, Literal, Protocol, overload

from matplotlib.figure import Figure

from .runtime import configure_matplotlib_environment


class MatplotlibAxesCollection(Protocol):
    def __iter__(self) -> Iterator["MatplotlibAxes"]: ...

    def __getitem__(self, index: int) -> "MatplotlibAxes": ...

    def __len__(self) -> int: ...

    @property
    def shape(self) -> tuple[int, ...]: ...

    @property
    def ndim(self) -> int: ...

    @property
    def flat(self) -> Iterator["MatplotlibAxes"]: ...

    def ravel(self) -> Any: ...

    def flatten(self) -> Any: ...


class MatplotlibAxes(Protocol):
    def plot(self, *args: Any, **kwargs: Any) -> Any: ...

    def scatter(self, *args: Any, **kwargs: Any) -> Any: ...

    def bar(self, *args: Any, **kwargs: Any) -> Any: ...

    def barh(self, *args: Any, **kwargs: Any) -> Any: ...

    def imshow(self, *args: Any, **kwargs: Any) -> Any: ...

    def fill_between(self, *args: Any, **kwargs: Any) -> Any: ...

    def grid(self, *args: Any, **kwargs: Any) -> Any: ...

    def legend(self, *args: Any, **kwargs: Any) -> Any: ...

    def text(self, *args: Any, **kwargs: Any) -> Any: ...

    def annotate(self, *args: Any, **kwargs: Any) -> Any: ...

    def axhline(self, *args: Any, **kwargs: Any) -> Any: ...

    def axvline(self, *args: Any, **kwargs: Any) -> Any: ...

    def axis(self, *args: Any, **kwargs: Any) -> Any: ...

    def set_title(self, *args: Any, **kwargs: Any) -> Any: ...

    def set_xlabel(self, *args: Any, **kwargs: Any) -> Any: ...

    def set_ylabel(self, *args: Any, **kwargs: Any) -> Any: ...

    def set_xlim(self, *args: Any, **kwargs: Any) -> Any: ...

    def set_ylim(self, *args: Any, **kwargs: Any) -> Any: ...

    def set_xticks(self, *args: Any, **kwargs: Any) -> Any: ...

    def set_yticks(self, *args: Any, **kwargs: Any) -> Any: ...

    def set_xticklabels(self, *args: Any, **kwargs: Any) -> Any: ...

    def set_yticklabels(self, *args: Any, **kwargs: Any) -> Any: ...

    def set_visible(self, *args: Any, **kwargs: Any) -> Any: ...

    def set_axisbelow(self, *args: Any, **kwargs: Any) -> Any: ...

    def tick_params(self, *args: Any, **kwargs: Any) -> Any: ...

    def twiny(self) -> "MatplotlibAxes": ...

    def twinx(self) -> "MatplotlibAxes": ...

    def add_patch(self, *args: Any, **kwargs: Any) -> Any: ...

    def table(self, *args: Any, **kwargs: Any) -> Any: ...

    @property
    def transAxes(self) -> Any: ...


class MatplotlibPyplot(Protocol):
    @overload
    def subplots(self, nrows: Literal[1] = 1, ncols: Literal[1] = 1, *args: Any, **kwargs: Any) -> tuple[Figure, MatplotlibAxes]: ...

    @overload
    def subplots(self, nrows: int, ncols: int = 1, *args: Any, **kwargs: Any) -> tuple[Figure, MatplotlibAxesCollection]: ...

    def figure(self, *args: Any, **kwargs: Any) -> Figure: ...

    def close(self, fig: Figure | None = None) -> None: ...

    def __getattr__(self, name: str) -> Any: ...


configure_matplotlib_environment()
import matplotlib

matplotlib.use("Agg")
from matplotlib import pyplot as _pyplot

plt: Any = _pyplot


def prepare_matplotlib() -> Any:
    return plt


def write_plot(fig: Figure, path: Path, *, dpi: int = 160, close: bool = True) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        fig.savefig(path, format="png", dpi=dpi, bbox_inches="tight")
    finally:
        if close:
            plt.close(fig)


def figure_to_png_bytes(fig: Figure, *, dpi: int = 160, close: bool = True) -> bytes:
    buffer = BytesIO()
    try:
        fig.savefig(buffer, format="png", dpi=dpi, bbox_inches="tight")
        return buffer.getvalue()
    finally:
        if close:
            plt.close(fig)


def _figure_to_png(fig: Figure) -> bytes:
    return figure_to_png_bytes(fig)
